# Generated by Django 4.0.3 on 2022-03-16 16:26

import control_plane.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuningInstance',
            fields=[
                ('primary_url', models.CharField(max_length=30)),
                ('primary_port', models.CharField(max_length=5)),
                ('replica_url', models.CharField(max_length=30)),
                ('replica_port', models.CharField(max_length=5)),
                ('uuid', models.CharField(default=control_plane.models.autogenerate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('state', models.JSONField(default=control_plane.models.tuningInstance_state_default, verbose_name='state')),
            ],
        ),
    ]
