# Generated by Django 4.0.3 on 2022-04-17 14:13

import control_plane.services.exploratory_worker_handler.exploratory_pg_status_types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_plane", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExploratoryPGInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tuning_id", models.CharField(max_length=36)),
                ("launch_event_name", models.CharField(max_length=120)),
                ("exploratory_pg_port", models.IntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                control_plane.services.exploratory_worker_handler.exploratory_pg_status_types.ExploratoryPGStatusType[
                                    "PENDING"
                                ],
                                "PENDING",
                            ),
                            (
                                control_plane.services.exploratory_worker_handler.exploratory_pg_status_types.ExploratoryPGStatusType[
                                    "READY"
                                ],
                                "READY",
                            ),
                            (
                                control_plane.services.exploratory_worker_handler.exploratory_pg_status_types.ExploratoryPGStatusType[
                                    "STOPPED"
                                ],
                                "STOPPED",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
            ],
        ),
    ]
