from enum import Enum


class EventHandlerType(str, Enum):

    PRIMARY_WORKER_HANDLER = "PRIMARY_WORKER_HANDLER"
    EXPLORATORY_WORKER_HANDLER = "EXPLORATORY_WORKER_HANDLER"
    RESOURCE_HANDLER = "RESOURCE_HANDLER"
    TUNING_MODULE = "TUNING_MODULE"
    INTELLIGENCE_MODULE = "INTELLIGENCE_MODULE"
