# Generated by Django 4.1.1 on 2022-09-07 22:10

import database_manager.database_state_types
import database_manager.models
from django.db import migrations, models
import environment_manager.environment_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('database_id', models.CharField(default=database_manager.models.autogenerate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('environment_type', models.CharField(choices=[(environment_manager.environment_types.EnvironmentType['SELF_MANAGED_POSTGRES'], 'Self managed postgres'), (environment_manager.environment_types.EnvironmentType['AWS_RDS_POSTGRES'], 'AWS RDS Postgres')], max_length=120)),
                ('active', models.BooleanField(default=False)),
                ('self_managed_postgres_config', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[(database_manager.database_state_types.DatabaseStateType['REGISTERING'], 'REGISTERING'), (database_manager.database_state_types.DatabaseStateType['HEALTHY'], 'HEALTHY'), (database_manager.database_state_types.DatabaseStateType['UNHEALTHY'], 'UNHEALTHY'), (database_manager.database_state_types.DatabaseStateType['TUNING'], 'TUNING'), (database_manager.database_state_types.DatabaseStateType['COLLECTING_WORKLOAD'], 'COLLECTING_WORKLOAD'), (database_manager.database_state_types.DatabaseStateType['COLLECTING_METRICS'], 'COLLECTING_METRICS'), (database_manager.database_state_types.DatabaseStateType['COLLECTING_STATE'], 'COLLECTING_STATE')], max_length=120)),
            ],
        ),
    ]
