# Generated by Django 4.1.1 on 2022-09-09 11:57

import database_manager.database_state_types
import database_manager.models
import database_manager.services.command_queue.models
import django.contrib.postgres.fields
import django.db.models.deletion
import environments.environment_types
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resource_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "command_id",
                    models.CharField(
                        default=database_manager.services.command_queue.models.autogenerate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("database_id", models.CharField(max_length=36)),
                (
                    "parent_command_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=36),
                        blank=True,
                        size=None,
                    ),
                ),
                ("command_type", models.CharField(max_length=120)),
                ("completed", models.BooleanField(default=False)),
                ("config", models.JSONField(default=dict, verbose_name="config")),
            ],
        ),
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "database_id",
                    models.CharField(
                        default=database_manager.models.autogenerate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "environment_type",
                    models.CharField(
                        choices=[
                            (
                                environments.environment_types.EnvironmentType[
                                    "SELF_MANAGED_POSTGRES"
                                ],
                                "Self managed postgres",
                            ),
                            (
                                environments.environment_types.EnvironmentType[
                                    "AWS_RDS_POSTGRES"
                                ],
                                "AWS RDS Postgres",
                            ),
                        ],
                        max_length=120,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            (
                                database_manager.database_state_types.DatabaseStateType[
                                    "REGISTERING"
                                ],
                                "REGISTERING",
                            ),
                            (
                                database_manager.database_state_types.DatabaseStateType[
                                    "HEALTHY"
                                ],
                                "HEALTHY",
                            ),
                            (
                                database_manager.database_state_types.DatabaseStateType[
                                    "UNHEALTHY"
                                ],
                                "UNHEALTHY",
                            ),
                            (
                                database_manager.database_state_types.DatabaseStateType[
                                    "TUNING"
                                ],
                                "TUNING",
                            ),
                            (
                                database_manager.database_state_types.DatabaseStateType[
                                    "COLLECTING_WORKLOAD"
                                ],
                                "COLLECTING_WORKLOAD",
                            ),
                            (
                                database_manager.database_state_types.DatabaseStateType[
                                    "COLLECTING_METRICS"
                                ],
                                "COLLECTING_METRICS",
                            ),
                            (
                                database_manager.database_state_types.DatabaseStateType[
                                    "COLLECTING_STATE"
                                ],
                                "COLLECTING_STATE",
                            ),
                        ],
                        max_length=120,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelfManagedPostgresConfig",
            fields=[
                (
                    "database",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="database_manager.database",
                    ),
                ),
                ("primary_host", models.CharField(max_length=120)),
                ("primary_ssh_port", models.CharField(max_length=120)),
                ("primary_ssh_user", models.CharField(max_length=120)),
                ("primary_pg_user", models.CharField(max_length=120)),
                ("primary_pg_port", models.CharField(max_length=120)),
                ("replica_host", models.CharField(max_length=120)),
                ("replica_ssh_port", models.CharField(max_length=120)),
                ("replica_ssh_user", models.CharField(max_length=120)),
                ("replica_pg_user", models.CharField(max_length=120)),
                ("replica_pg_port", models.CharField(max_length=120)),
                (
                    "primary_ssh_key",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_ssh_key",
                        to="resource_manager.resource",
                    ),
                ),
                (
                    "replica_ssh_key",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replica_ssh_key",
                        to="resource_manager.resource",
                    ),
                ),
            ],
        ),
    ]
