# Generated by Django 4.1.2 on 2022-10-31 18:14

import database_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuningAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuning_action_id', models.CharField(default=database_manager.models.autogenerate_uuid, max_length=36)),
                ('tuning_instance_id', models.CharField(max_length=36)),
                ('command', models.CharField(max_length=512)),
                ('benefit', models.FloatField()),
                ('reboot_required', models.BooleanField(default=False)),
            ],
        ),
    ]
