# Generated by Django 4.1.2 on 2022-11-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0002_tuninginstance_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuninginstance',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
