# Generated by Django 4.1.1 on 2022-09-22 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0002_database_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
