# Generated by Django 4.1.2 on 2022-10-13 16:06

import database_manager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0001_initial'),
        ('database_manager', '0003_database_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(default=database_manager.models.autogenerate_uuid, max_length=36)),
                ('database_id', models.CharField(max_length=36)),
                ('available', models.BooleanField(default=False)),
                ('action_name', models.CharField(blank=True, max_length=120)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_id', to='resource_manager.resource')),
                ('workload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_id', to='resource_manager.resource')),
            ],
        ),
    ]
