# Generated by Django 4.1.2 on 2022-10-14 03:56

import database_manager.models
import database_manager.types.tuningstatus
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0001_initial'),
        ('database_manager', '0004_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuningInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuning_instance_id', models.CharField(default=database_manager.models.autogenerate_uuid, max_length=36)),
                ('database_id', models.CharField(max_length=36)),
                ('status', models.CharField(choices=[(database_manager.types.tuningstatus.TuningStatusType['RUNNING'], 'RUNNING'), (database_manager.types.tuningstatus.TuningStatusType['FINISHED'], 'FINISHED'), (database_manager.types.tuningstatus.TuningStatusType['FAILED'], 'FAILED')], max_length=32)),
                ('action_name', models.CharField(blank=True, max_length=120)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_id', to='resource_manager.resource')),
                ('workload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_id', to='resource_manager.resource')),
            ],
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
