from enum import Enum


class CommandType(str, Enum):

    REGISTER_DATABASE = "REGISTER_DATABASE"
    LAUNCH_PRIMARY_DAEMON = "LAUNCH_PRIMARY_DAEMON"
    LAUNCH_REPLICA_DAEMON = "LAUNCH_REPLICA_DAEMON"
