SERVER_MODE_ENV_VAR_KEY = "SERVER_MODE"

SERVER_MODE_CONTROL_PLANE = "CONTROL_PLANE"
SERVER_MODE_PRIMARY_WORKER = "PRIMARY_WORKER"
SERVER_MODE_EXPLORATORY_WORKER = "EXPLORATORY_WORKER"

AMPQ_USER_ENV_VAR_KEY = "AMPQ_USER"
AMPQ_PASSWORD_ENV_VAR_KEY = "AMPQ_PASSWORD"
AMPQ_URL_ENV_VAR_KEY = "AMPQ_URL"
AMPQ_PORT_ENV_VAR_KEY = "AMPQ_PORT"
