from enum import Enum

class DatabaseStateType(str, Enum):

    REGISTERING = "REGISTERING"

    HEALTHY = "HEALTHY"
    UNHEALTHY = "UNHEALTHY"

    TUNING = "TUNING"
    COLLECTING_WORKLOAD = "COLLECTING_WORKLOAD"
    COLLECTING_METRICS = "COLLECTING_METRICS"
    COLLECTING_STATE = "COLLECTING_STATE"


