# Generated by Django 4.1.2 on 2022-11-01 01:39

from django.db import migrations, models
import resource_manager.models
import resource_manager.resource_type


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(default=resource_manager.models.autogenerate_uuid, max_length=36)),
                ('database_id', models.CharField(max_length=36)),
                ('friendly_name', models.CharField(max_length=512, unique=True)),
                ('available_at', models.DateTimeField(null=True)),
                ('metadata', models.JSONField()),
                ('resource_type', models.CharField(choices=[(resource_manager.resource_type.ResourceType['KEY'], 'KEY'), (resource_manager.resource_type.ResourceType['WORKLOAD'], 'WORKLOAD'), (resource_manager.resource_type.ResourceType['STATE'], 'STATE')], max_length=32)),
                ('available', models.BooleanField(default=False)),
                ('resource_name', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
