# Generated by Django 4.1.1 on 2022-09-09 11:57

import resource_manager.models
import resource_manager.resource_type
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        default=resource_manager.models.autogenerate_uuid, max_length=36
                    ),
                ),
                ("database_id", models.CharField(max_length=36)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            (resource_manager.resource_type.ResourceType["KEY"], "KEY"),
                            (
                                resource_manager.resource_type.ResourceType["WORKLOAD"],
                                "WORKLOAD",
                            ),
                            (
                                resource_manager.resource_type.ResourceType["STATE"],
                                "STATE",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("available", models.BooleanField(default=False)),
                ("resource_name", models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
