# Generated by Django 4.1.2 on 2022-11-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='collected_at',
            field=models.DateTimeField(null=True),
        ),
    ]
