# Generated by Django 4.1.2 on 2022-11-01 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0002_resource_collected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='collected_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
