from enum import Enum


class CommandType(str, Enum):

    LAUNCH_PRIMARY_WORKER = "LAUNCH_PRIMARY_WORKER"
    CAPTURE_PRIMARY_WORKLOAD = "CAPTURE_PRIMARY_WORKLOAD"

    LAUNCH_EXPLORATORY_WORKER = "LAUNCH_EXPLORATORY_WORKER"
    LAUNCH_EXPLORATORY_POSTGRES = "LAUNCH_EXPLORATORY_POSTGRES"
    STOP_EXPLORATORY_POSTGRES = "STOP_EXPLORATORY_POSTGRES"

    COLLECT_DATA_FROM_EXPLORATORY = "COLLECT_DATA_FROM_EXPLORATORY"

    START_TUNING = "START_TUNING"
