"""
Django settings for control_plane project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

RESOURCE_DIR = BASE_DIR / "database_manager" / "resources"

SCRIPTS_DIR = BASE_DIR / "scripts"
LAUNCH_PRIMARY_DAEMON_SCRIPT = SCRIPTS_DIR / "launch_primary_daemon.sh"
LAUNCH_REPLICA_DAEMON_SCRIPT = SCRIPTS_DIR / "launch_replica_daemon.sh"

# Control plane base url for primary / replica daemons callbacks
CONTROL_PLANE_CALLBACK_BASE_URL = "http://ec2-3-87-186-24.compute-1.amazonaws.com:8000"  # Kush's EC2 instance
# CONTROL_PLANE_CALLBACK_BASE_URL = "http://ec2-54-82-252-113.compute-1.amazonaws.com"  # Tim's EC2 instance

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cmjr$4esu!k-r4$$+$s1$8wbjx_^7i28y!8xm@e=1!lgkfb-fv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]

INSTALLED_APPS += [
    'database_manager',
    'environments',
    'resource_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True  # SECURITY WARNING: Remove this in production

ROOT_URLCONF = 'control_plane.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'control_plane.wsgi.application'


"""
Housekeeping database config (postgres). Setup:
    - CREATE USER cmudb WITH superuser ENCRYPTED PASSWORD 'cmudb@2021';
    - CREATE DATABASE noisepage_control WITH OWNER cmudb ENCODING 'UTF8';

Setup admin only on CONTROL_PLANE
"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "noisepage_control",
        "USER": "cmudb",
        "PASSWORD": "cmudb@2021",
        "HOST": "localhost",
        "PORT": "5432",
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING_DIR = BASE_DIR / "logs"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "control_plane_info": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOGGING_DIR / "control_plane_info.log",
            "formatter": "verbose",
        },
        "control_plane_debug": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": LOGGING_DIR / "control_plane_debug.log",
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "control_plane": {
            "handlers": ["control_plane_info", "control_plane_debug"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}
