#!/bin/sh

# Start postgres
service postgresql start

# Create user
echo "CREATE USER ${PG_USERNAME} WITH SUPERUSER;" | psql

# Create HypoPG extension
echo "CREATE EXTENSION hypopg;" | psql

# Restore schema; /ddl_dump.sql should be mounted while execing 
# psql postgres -U ${PG_USERNAME} < /data/ddl_dump.sql 

# Restore schema + data; /data.tar should be mounted while execing
# /data_dump.tar should be generated by 'pg_dump -U postgres -p PORT -F t DB_NAME > data_dump.tar'
pg_restore -U ${PG_USERNAME} -F t -d postgres < /data/data_dump.tar

# TODO: This is a hack to delete all ';' in workload.csv because index_selection tool can't parse it
sed -i 's/;/./g' /data/workload.csv

# Move to directory
cd /noisepage-pilot/action/generation

# Run tuning engine
python3 engine.py -o search_space.json -c /data/garbage_config.yaml

# Move generated file to mounted directory
mv search_space.json /data/

cd /index_selection_evaluation/
python3 -m selection /data/index_config.json

# Move results to mounted directory
mv benchmark_results /data/