SERVER_MODE_ENV_VAR_KEY = "SERVER_MODE"
SERVER_MODE_CONTROL_PLANE = "CONTROL_PLANE"
SERVER_MODE_PRIMARY_WORKER = "PRIMARY_WORKER"
SERVER_MODE_EXPLORATORY_WORKER = "EXPLORATORY_WORKER"

CONTROL_PLANE_URL_ENV_KEY = "CONTROL_PLANE_URL"
CONTROL_PLANE_PORT_ENV_KEY = "CONTROL_PLANE_PORT"

AMPQ_USER_ENV_VAR_KEY = "AMPQ_USER"
AMPQ_PASSWORD_ENV_VAR_KEY = "AMPQ_PASSWORD"
AMPQ_URL_ENV_VAR_KEY = "AMPQ_URL"
AMPQ_PORT_ENV_VAR_KEY = "AMPQ_PORT"

TUNING_ID_ENV_VAR_KEY = "TUNING_ID"
LAUNCH_EVENT_NAME_ENV_VAR_KEY = "LAUNCH_EVENT_NAME"

PRIMARY_DB_PORT_ENV_VAR_KEY = "PRIMARY_DB_PORT"
REPLICA_DB_PORT_ENV_VAR_KEY = "REPLICA_DB_PORT"
PRIMARY_DB_USERNAME_ENV_VAR_KEY = "PRIMARY_DB_USERNAME"
REPLICA_DB_USERNAME_ENV_VAR_KEY = "REPLICA_DB_USRNAME"
